<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="9176" started-at="2020-03-07T19:31:17Z" finished-at="2020-03-07T19:31:26Z">
    <groups>
    </groups>
    <test name="CreateCustomerAPITest" duration-ms="9176" started-at="2020-03-07T19:31:17Z" finished-at="2020-03-07T19:31:26Z">
      <class name="com.restassured.testcases.CreateCustomerTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.restassured.testcases.CreateCustomerTest@1f59a598]" name="setUp" is-config="true" duration-ms="406" started-at="2020-03-07T19:31:17Z" finished-at="2020-03-07T19:31:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="validateCreateCustomerAPIWithInvalidSecretkey(java.util.Hashtable)[pri:0, instance:com.restassured.testcases.CreateCustomerTest@1f59a598]" name="validateCreateCustomerAPIWithInvalidSecretkey" duration-ms="6499" started-at="2020-03-07T19:31:17Z" data-provider="data" finished-at="2020-03-07T19:31:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=sood07deepak@abc.com, name=Deepak Sood, description=This is description}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [401]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.restassured.testcases.CreateCustomerTest.validateCreateCustomerAPIWithInvalidSecretkey(CreateCustomerTest.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateCustomerAPIWithInvalidSecretkey -->
        <test-method status="PASS" signature="validateCreateCustomerAPIWithValidSecretkey(java.util.Hashtable)[pri:0, instance:com.restassured.testcases.CreateCustomerTest@1f59a598]" name="validateCreateCustomerAPIWithValidSecretkey" duration-ms="1771" started-at="2020-03-07T19:31:24Z" data-provider="data" finished-at="2020-03-07T19:31:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=sood07deepak@abc.com, name=Deepak, description=This is description}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateCustomerAPIWithValidSecretkey -->
        <test-method status="PASS" signature="validateCreateCustomerAPIWithValidSecretkey(java.util.Hashtable)[pri:0, instance:com.restassured.testcases.CreateCustomerTest@1f59a598]" name="validateCreateCustomerAPIWithValidSecretkey" duration-ms="2132" started-at="2020-03-07T19:31:24Z" data-provider="data" finished-at="2020-03-07T19:31:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=abc@abc.com, name=Rahul, description=Description 3}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateCustomerAPIWithValidSecretkey -->
        <test-method status="PASS" signature="validateCreateCustomerAPIWithValidSecretkey(java.util.Hashtable)[pri:0, instance:com.restassured.testcases.CreateCustomerTest@1f59a598]" name="validateCreateCustomerAPIWithValidSecretkey" duration-ms="2594" started-at="2020-03-07T19:31:24Z" data-provider="data" finished-at="2020-03-07T19:31:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=abc@abc.com, name=Champ, description=Description}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateCustomerAPIWithValidSecretkey -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.restassured.testcases.CreateCustomerTest@1f59a598]" name="tearDown" is-config="true" duration-ms="1" started-at="2020-03-07T19:31:27Z" finished-at="2020-03-07T19:31:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.restassured.testcases.CreateCustomerTest -->
    </test> <!-- CreateCustomerAPITest -->
  </suite> <!-- Suite -->
</testng-results>
